<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Profile</name>
   <tag></tag>
   <elementGuidId>33b9fcdc-3eb5-4822-812a-041905d16040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-item-3 > p.bottom-nav-item--title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-item-3']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>04252e5d-8a81-4cdc-9851-90f6caf28928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bottom-nav-item--title</value>
      <webElementGuid>0785527f-fa8e-4eb9-b787-429825f4440f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>1d187920-cc7a-4ce8-8e44-15e73a5e3416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-item-3&quot;)/p[@class=&quot;bottom-nav-item--title&quot;]</value>
      <webElementGuid>0121d9ec-0ef5-4179-8ae7-b0e88488bf00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-item-3']/p</value>
      <webElementGuid>35803f4e-3615-47a8-9b10-fdcee24e0ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All rights reserved.'])[1]/following::p[4]</value>
      <webElementGuid>fd6d1696-ad0e-47e8-a5c2-e361e3037eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kunjungi Website Astra Otoparts'])[1]/following::p[4]</value>
      <webElementGuid>7de086d4-56c0-4164-8798-abb0a7fc97c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'nav-item-3', '&quot;', ')/p[@class=', '&quot;', 'bottom-nav-item--title', '&quot;', ']')])[1]/preceding::p[1]</value>
      <webElementGuid>5bf39579-daef-467e-be00-b03d3166dafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profile']/parent::*</value>
      <webElementGuid>147ba120-0381-41f5-a5c2-43858192e02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/p</value>
      <webElementGuid>6bec8dbe-c336-47f8-8c8f-3761184c3490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Profile' or . = 'Profile')]</value>
      <webElementGuid>df830ca6-bee4-4483-b7fe-673aecf1e111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
