<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Keluar</name>
   <tag></tag>
   <elementGuidId>96560f96-a545-4e41-8603-8e1339bcda58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/div[2]/div/a[5]/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ed148e2d-f5ad-49da-ad3a-8d499b4ed6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>198b3e95-dd1e-43ba-938b-54d5d8d40f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>618a7a98-03a6-4de9-ad76-09715bbde6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>letter-spacing</name>
      <type>Main</type>
      <value>-0.5</value>
      <webElementGuid>0f26f5fc-9349-4802-b274-a88ae47b268c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-w647qe-0 iPPeqj</value>
      <webElementGuid>30a89fd6-d68d-4364-81f5-be6f9a357568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>a583aaa1-8817-4b2e-932e-93db8133f459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-1crxk01-0 lkwwJy sc-1008z3r-0 jeqDnW&quot;]/div[@class=&quot;sc-1crxk01-0 bjsXSt sc-1bqqgbt-0 kKmybO&quot;]/div[@class=&quot;sc-1crxk01-0 hGLyWJ sc-1umjua2-0 nFBTd&quot;]/a[5]/div[@class=&quot;sc-1crxk01-0 hBGxiZ&quot;]/div[@class=&quot;sc-1crxk01-0 DxRlE&quot;]/span[@class=&quot;sc-w647qe-0 iPPeqj&quot;]</value>
      <webElementGuid>509d889d-acd5-4dc6-a089-52d3e98dd07e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/div[2]/div/a[5]/div/div/span[2]</value>
      <webElementGuid>fa6d1ff8-5eee-4de5-be56-17174eadcdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun Sosial Saya'])[1]/following::span[3]</value>
      <webElementGuid>39f17012-320b-4c9d-a04d-59c3f1e91b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Kata Sandi'])[1]/following::span[5]</value>
      <webElementGuid>82ab8f9b-df3e-4b51-88b8-bf7a608d790c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All rights reserved.'])[1]/preceding::span[1]</value>
      <webElementGuid>b7881307-d652-44b5-961d-e66311b0b131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>ce08f138-86fb-4ced-a5d6-909310171cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/div/div/span[2]</value>
      <webElementGuid>9b4c5452-aa8b-4c20-b574-a917f194e1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>15f21889-b948-4c4a-acf0-a7afc8222374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
