<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_All rights reserved_sc-22dkih-2 htMicR</name>
   <tag></tag>
   <elementGuidId>4350f41b-65f0-400b-8e4c-27177fafeb91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-22dkih-2.htMicR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='portal']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>00518070-386f-450a-ab1f-9c4d8f4208b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-22dkih-2 htMicR</value>
      <webElementGuid>6fa77ccf-0f6d-4236-880a-9bec173cb5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portal&quot;)/div[@class=&quot;sc-1crxk01-0 lkwwJy sc-22dkih-0 kgwAUW&quot;]/div[@class=&quot;sc-22dkih-2 htMicR&quot;]</value>
      <webElementGuid>98ac953f-2fad-4177-bfc0-36a6a7509213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portal']/div[2]/div</value>
      <webElementGuid>68c5ad36-ee32-45f0-8b0d-064ff30a2475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div[2]/div</value>
      <webElementGuid>572167db-4eef-497d-b27c-5c1582f8ea28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
