<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Stok tersedia_sc-dfsrp1-17 dGwcMx</name>
   <tag></tag>
   <elementGuidId>43d37a92-2e85-4af8-a2d3-5c18f7848b11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/section/div[5]/div/div[4]/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7eabf1f0-5972-42ad-a0c1-d09a69a5e541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://newb2c.astraotoparts.co.id/asset/product/import/g/s/gs_warranty_1.jpg</value>
      <webElementGuid>96a58644-cfa8-40b4-a057-89505300ae1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Product Item</value>
      <webElementGuid>686f0895-c284-4c2f-bdc4-168f0f2534f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dfsrp1-17 dGwcMx</value>
      <webElementGuid>f733026b-b23e-489b-97cc-60e7483ca8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-9oqgzk-0 cmGYbp&quot;]/section[@class=&quot;sc-9oqgzk-1 jJgBno&quot;]/div[@class=&quot;sc-1crxk01-0 lkwwJy&quot;]/div[@class=&quot;sc-1crxk01-0 jkvoMP&quot;]/div[4]/div[1]/div[2]/div[@class=&quot;sc-1crxk01-0 lkwwJy sc-dfsrp1-1 cOOIyQ&quot;]/div[@class=&quot;sc-dfsrp1-16 aUZEl&quot;]/img[@class=&quot;sc-dfsrp1-17 dGwcMx&quot;]</value>
      <webElementGuid>a23f57c0-791f-4d6b-8528-2e8a97e5bdc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/section/div[5]/div/div[4]/div/div[2]/div/div/img</value>
      <webElementGuid>1da38ef1-e5c3-4968-a02a-faf9f48864f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Product Item'])[2]</value>
      <webElementGuid>9b4b4a67-9cdd-43a7-bd0d-2c87e6ad17d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>b3c34501-f5cd-4165-b38c-980c47ba22d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://newb2c.astraotoparts.co.id/asset/product/import/g/s/gs_warranty_1.jpg' and @alt = 'Product Item']</value>
      <webElementGuid>ac820880-f74a-4028-9b95-c0cfd59f5d13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
