<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bisnis_sc-1hxhqap-2 jOfcLH</name>
   <tag></tag>
   <elementGuidId>5c4a9563-b011-48e1-8024-00b8b36db373</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/section/section/div/div[5]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>323600f5-e993-4f8d-82d1-82e349817122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://newb2c.astraotoparts.co.id/asset/aop/lainnya.png</value>
      <webElementGuid>8eea40fc-4270-4462-81d7-86de5da8a8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1hxhqap-2 jOfcLH</value>
      <webElementGuid>b5d3b612-9a35-459f-b8e2-f3c6080d00e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-1dze5zo-0 lnpKeT&quot;]/section[@class=&quot;sc-1dze5zo-1 imPRYC&quot;]/section[@class=&quot;sc-60zcpy-1 klCJsD&quot;]/div[@class=&quot;sc-1crxk01-0 ksZDNo sc-10b1rua-3 hRIagK&quot;]/div[@class=&quot;sc-1crxk01-0 gepUjx sc-1hxhqap-0 fFaRKu&quot;]/div[@class=&quot;sc-1hxhqap-3 btnGPj&quot;]/img[@class=&quot;sc-1hxhqap-2 jOfcLH&quot;]</value>
      <webElementGuid>00657965-e9d4-4d61-9b60-ab749f69a506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/section/section/div/div[5]/div/img</value>
      <webElementGuid>c5056cc2-b63a-41f7-a877-653fb704d3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://newb2c.astraotoparts.co.id/asset/aop/lainnya.png')]</value>
      <webElementGuid>579f218a-a87f-4ebb-9447-2c6689302d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/img</value>
      <webElementGuid>45e67e4b-94af-4d0b-add4-e7b2248e87dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://newb2c.astraotoparts.co.id/asset/aop/lainnya.png']</value>
      <webElementGuid>99e5c6cd-5315-4444-ac94-ecc52db2a253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
