<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Baca Selengkapnya</name>
   <tag></tag>
   <elementGuidId>d04ee6b3-2b17-4cfd-a24c-76637bf8735d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sc-w647qe-0.YEUNd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/section/section[2]/div[3]/div[3]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0d847aa6-6c46-485d-b23f-2b01c6dad5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>33d74958-a87e-49e7-ba70-a3366630279f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>f19db2b1-5744-4f92-9ddf-047a36b7e265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-w647qe-0 YEUNd</value>
      <webElementGuid>1bb97272-0980-4614-a332-2d98fa24af42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baca Selengkapnya</value>
      <webElementGuid>0656365f-1fee-40b3-9ffe-deb94b94f0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-pk5e3p-0 fQUczW&quot;]/section[@class=&quot;sc-pk5e3p-1 ghbFQU&quot;]/section[@class=&quot;sc-16gfu33-2 kEfuEQ&quot;]/div[@class=&quot;sc-1crxk01-0 lkwwJy sc-mkl3gx-0 jkPCzK&quot;]/div[@class=&quot;sc-1crxk01-0 gVKylD sc-mkl3gx-1 cJpzQJ&quot;]/div[@class=&quot;sc-1npuvvg-0 kLDupQ&quot;]/div[@class=&quot;sc-1crxk01-0 dmjeEM&quot;]/span[@class=&quot;sc-w647qe-0 YEUNd&quot;]</value>
      <webElementGuid>0b1eb427-1a46-4aac-80e2-ab5257dc06cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/section/section[2]/div[3]/div[3]/div/div/span</value>
      <webElementGuid>6b913d4d-6795-4695-a7c2-1990b866f015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*) E-Voucher yang sudah dibeli tidak dapat diretur dengan alasan apapun.'])[1]/following::span[1]</value>
      <webElementGuid>43fe9df2-e90a-4b22-ac10-51056d2c0540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motoquick Home Delivery'])[1]/following::span[3]</value>
      <webElementGuid>18e1d675-5c6d-4fb9-9b99-d09e218458e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ulasan Pengguna'])[1]/preceding::span[1]</value>
      <webElementGuid>7137662e-5fec-4bdf-b57f-f22ea04d26a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada ulasan'])[1]/preceding::span[2]</value>
      <webElementGuid>83954506-c6d3-49cf-b656-0ec59f1c47de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Baca Selengkapnya']/parent::*</value>
      <webElementGuid>4b73a0a8-4aa1-4acf-9e82-45b75e581d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span</value>
      <webElementGuid>66b9249b-8008-4d93-b808-26b27174fceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Baca Selengkapnya' or . = 'Baca Selengkapnya')]</value>
      <webElementGuid>e0f2a0ae-67b4-4484-a978-2b7de5d008ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
